// <auto-generated />
namespace ExampleCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addtblCategoriesProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtblCategoriesProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "201801260750161_add tbl Categories+Product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
