// <auto-generated />
namespace ExampleCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addtblNulable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtblNulable));
        
        string IMigrationMetadata.Id
        {
            get { return "201801281126349_add tbl Nulable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
